print()
print()
print()
# n1=int(input("digite um valor"))
print("digite um numero")
print()
n1=int(input(""))
print()
print()
print()

# n2=int(input("digite outro valor"))
print("digite outro")
print()
n2=int(input(""))
print()
print()
print()

s=n1 + n2
# print("a soma entre",n1,"e",n2,"vale",s)
print("<a soma entre {} e {} vale: {}>".format(n1, n2, s))
R=s + s
print("<{} + {} vale: {}>".format(s,s,R))
L=R * R
print(f"<{R} vezes {R} é: {L}>")
print()
print("<agora vamos para a divisão>")

# A=int(input("digite um numero"))
print("digite um numero")
print()
A=int(input(""))
print()
print()
print()
print()
print()
# B=int(input("digite outro"))
print("digite outro")
print()
B=int(input(""))
O=A / B
print()
print()
print()
print()
print()
print()
print(f"{A} dividido por {B} é: {O}")
print()
print()
print()